// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(Say) {
    var babble, james, sayThis, user;
    babble = require('babble');
    james = babble.babbler('james');
    user = babble.babbler('user');
    sayThis = require('say-this');
    Say.hello = function(msg, cb) {
      james.listen(/hi|hello/).tell(function() {
        return "Good morning!";
      });
      return user.ask('james', msg, function(greeting) {
        return cb(null, greeting);
      });
    };
    Say.remoteMethod("hello", {
      accepts: {
        arg: 'msg',
        type: 'string'
      },
      returns: {
        arg: 'greeting',
        type: 'string'
      }
    });
    Say.speak = function(msg, data) {
      console.log(msg);
      james.listen(/hi|hello|good morning/).tell(function() {
        return "good morning sir... How are you? ";
      });
      return user.ask('james', msg, function(greeting) {
        var request;
        request = require('request');
        return request.get("http://localhost:3000/tts?phrase=" + greeting, function(error, response, body) {
          return data(null, body);
        });
      });
    };
    return Say.remoteMethod("speak", {
      http: {
        verb: 'get'
      },
      accepts: {
        arg: 'msg',
        type: 'string'
      },
      returns: {
        arg: 'data',
        type: 'object'
      }
    });
  };

}).call(this);

//# sourceMappingURL=say.js.map
