// Generated by CoffeeScript 1.8.0
(function() {
  var Trainer;

  Trainer = (function() {
    function Trainer(classifier) {
      var foo;
      this.classifier = classifier;
      foo = db.addCollection("" + this.classifier);
      foo.insert({
        name: 'test',
        phrase: 'this is a test',
        age: 12
      });
      db.saveToDisk();
      foo.data + 'ok';
    }

    Trainer.prototype.addPhrase = function(classifier, phrase, type) {
      var bar;
      this.classifier = classifier;
      bar = db.addCollection("" + this.classifier);
      this.classifier.insert({
        phrase: 'phrase',
        type: 'type'
      });
      this.classifier.insert({
        type: 'test'
      });
      db.saveToDisk();
      return console.log('ok');
    };

    return Trainer;

  })();

}).call(this);

//# sourceMappingURL=td.js.map
