// Generated by CoffeeScript 1.8.0
(function() {
  var app, boot, loopback;

  loopback = require('loopback');

  boot = require('loopback-boot');

  app = module.exports = loopback();

  boot(app, __dirname);

  module.exports = function(boot) {
    return app.get('/ping', function(req, res) {
      return res.send('pong bitches!');
    });
  };

}).call(this);

//# sourceMappingURL=ping.js.map
